import { StyleSheet, Dimensions } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';
import { Colors } from '../../../../constants/Colors';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FCFCFD',
  },
  topSection: {
    backgroundColor: Colors.brand[60],
    paddingHorizontal: scale(5),
    paddingBottom: verticalScale(52),
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  topNavWrapper: {
    width: '100%',
    paddingHorizontal: scale(0), // Kenarlara çok yakın
    marginHorizontal: scale(0),
    marginTop: verticalScale(40),
  },
  topNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(8),
  },
  leading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
  },
  avatarContainer: {
    width: scale(40),
    height: scale(40),
    borderRadius: 9999,
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  textContainer: {
    flexDirection: 'column',
  },
  greetingText: {
    fontFamily: 'DMSans-Medium',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.gray[5],
  },
  userName: {
    fontFamily: 'DMSans-SemiBold',
    fontSize: moderateScale(20),
    lineHeight: moderateScale(28),
    color: '#FFFFFF',
  },
  notificationButton: {
    position: 'relative',
  },
  notificationIcon: {
    width: scale(24),
    height: scale(24),
  },
  indicator: {
    position: 'absolute',
    width: scale(8),
    height: scale(8),
    right: -1,
    top: -1,
    backgroundColor: '#FF6565',
    borderRadius: 4,
  },
  mainContent: {
    alignItems: 'center',
    paddingVertical: verticalScale(10),
    gap: verticalScale(20),
  },
  topContent: {
    alignItems: 'center',
    gap: verticalScale(4),
  },
  mainTitle: {
    fontFamily: 'DMSans-ExtraBold',
    fontSize: moderateScale(48),
    lineHeight: moderateScale(56),
    textAlign: 'center',
    color: '#FFFFFF',
  },
  subtitle: {
    fontFamily: 'DMSans-Regular',
    fontSize: moderateScale(18),
    lineHeight: moderateScale(24),
    textAlign: 'center',
    color: Colors.brand[20],
  },
  metricsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(14),
  },
  metricCard: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(18),
    width: scale(100),
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#75d275',
    borderRadius: 16,
  },
  metricValue: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(26),
    lineHeight: moderateScale(32),
    textAlign: 'center',
    color: '#FFFFFF',
  },
  metricLabel: {
    fontFamily: 'DMSans-Medium',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    textAlign: 'center',
    color: Colors.brand[20],
  },
  content: {
    paddingHorizontal: scale(20),
    paddingBottom: verticalScale(16),
    gap: verticalScale(24),
  },
  cardMission: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: scale(18),
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    shadowColor: 'rgba(15, 23, 42, 0.12)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 1,
    elevation: 2,
    marginTop: verticalScale(20),
    position: 'absolute',
    top: verticalScale(-65),
    left: scale(20),
    right: scale(20),
  },
  cardTitle: {
    fontFamily: 'DMSans-SemiBold',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.gray[40],
  },
  cardSubtitle: {
    fontFamily: 'DMSans-Regular',
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    color: Colors.gray[30],
    maxWidth: width * 0.5,
  },
  checkInButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(6),
    paddingHorizontal: scale(12),
    gap: scale(8),
    backgroundColor: Colors.brand[60],
    borderRadius: 8,
    shadowColor: 'rgba(88, 182, 88, 0.3)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 5,
  },
  buttonText: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: '#FFFFFF',
  },
  arrowIcon: {
    width: scale(11),
    height: scale(11),
  },
  sectionHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionMain: {
    gap: verticalScale(2),
  },
  sectionTitle: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(16),
    lineHeight: moderateScale(22),
    color: Colors.gray[60],
  },
  cravingSection: {
    gap: verticalScale(8),
    marginTop: verticalScale(60),
  },
  assistanceList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  assistanceItem: {
    alignItems: 'center',
    gap: verticalScale(8),
  },
  assistanceIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(14),
    width: scale(56),
    height: scale(56),
    borderWidth: 1,
    borderColor: Colors.gray[10],
    borderRadius: 14,
  },
  iconImage: {
    width: scale(28),
    height: scale(28),
  },
  assistanceLabel: {
    fontFamily: 'DMSans-Medium',
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    textAlign: 'center',
    color: Colors.gray[30],
  },
  milestoneSection: {
    gap: verticalScale(8),
  },
  milestoneCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(16),
    gap: scale(12),
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    shadowColor: 'rgba(44, 44, 50, 0.06)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 3,
  },
  milestoneMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(16),
    flex: 1,
  },
  milestoneLeading: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  improvement: {
    alignItems: 'center',
    gap: verticalScale(4),
  },
  milestoneIcon: {
    width: scale(50),
    height: scale(50),
  },
  progressText: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    color: Colors.gray[60],
  },
  milestoneText: {
    flex: 1,
  },
  milestoneTitle: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(16),
    lineHeight: moderateScale(22),
    color: Colors.gray[60],
  },
  milestoneSubtitle: {
    fontFamily: 'DMSans-Regular',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.gray[30],
  },
  communitySection: {
    gap: verticalScale(8),
  },
  viewAllButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: scale(8),
  },
  viewAllText: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.brand[60],
  },
  postCard: {
    padding: scale(16),
    gap: verticalScale(12),
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    shadowColor: 'rgba(44, 44, 50, 0.06)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 3,
  },
  postTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  postLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  postAvatar: {
    width: scale(48),
    height: scale(48),
    borderRadius: 9999,
  },
  postUserInfo: {
    gap: verticalScale(4),
  },
  postUserName: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(16),
    lineHeight: moderateScale(22),
    color: Colors.gray[60],
  },
  postTime: {
    fontFamily: 'DMSans-Regular',
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    color: Colors.gray[40],
  },
  postOptions: {},
  optionsIcon: {
    width: scale(24),
    height: scale(24),
  },
  postBody: {
    gap: verticalScale(10),
  },
  postContent: {
    fontFamily: 'DMSans-Regular',
    fontSize: moderateScale(14),
    lineHeight: moderateScale(20),
    color: Colors.gray[60],
  },
  postImage: {
    width: '100%',
    height: verticalScale(170),
    backgroundColor: Colors.gray[10],
    borderRadius: 18,
  },
  postBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  postLeftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(16),
  },
  likes: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(2),
  },
  comments: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(2),
  },
  actionIcon: {
    width: scale(16),
    height: scale(16),
  },
  actionText: {
    fontFamily: 'DMSans-Bold',
    fontSize: moderateScale(13),
    lineHeight: moderateScale(16),
    color: Colors.gray[40],
  },
  postRightActions: {},
});