import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';
import { Colors } from '../../../../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(64),
    paddingHorizontal: scale(20),
  },
  card: {
    backgroundColor: Colors.gray[0],
    borderRadius: moderateScale(16),
    paddingVertical: verticalScale(48),
    paddingHorizontal: scale(24),
    width: '100%',
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: verticalScale(4),
    },
    shadowOpacity: 0.12,
    shadowRadius: moderateScale(8),
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  decorativeBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  gradientShape1: {
    position: 'absolute',
    top: -verticalScale(80),
    left: -scale(80),
    width: scale(250),
    height: verticalScale(200),
    borderRadius: scale(125),
    opacity: 0.15,
  },
  gradientShape2: {
    position: 'absolute',
    top: -verticalScale(60),
    right: -scale(100),
    width: scale(280),
    height: verticalScale(240),
    borderRadius: scale(140),
    opacity: 0.12,
  },
  gradientShape3: {
    position: 'absolute',
    bottom: verticalScale(20),
    left: -scale(50),
    width: scale(200),
    height: verticalScale(180),
    borderRadius: scale(100),
    opacity: 0.1,
  },
  gradientShape4: {
    position: 'absolute',
    top: '45%',
    right: -scale(120),
    width: scale(180),
    height: verticalScale(120),
    borderRadius: scale(90),
    opacity: 0.08,
    transform: [{ rotate: '270deg' }],
  },
  decorativeIcons: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  decorativeStar1: {
    position: 'absolute',
    top: verticalScale(60),
    right: scale(40),
    width: scale(24),
    height: scale(24),
    opacity: 0.4,
  },
  decorativeStar2: {
    position: 'absolute',
    top: verticalScale(120),
    left: scale(30),
    width: scale(20),
    height: scale(20),
    opacity: 0.3,
  },
  decorativeHeart1: {
    position: 'absolute',
    top: verticalScale(180),
    right: scale(60),
    width: scale(18),
    height: scale(18),
    opacity: 0.35,
  },
  decorativeCrown: {
    position: 'absolute',
    top: verticalScale(40),
    left: scale(50),
    width: scale(22),
    height: scale(22),
    opacity: 0.3,
  },
  celebrationIcons: {
    position: 'relative',
    width: '100%',
    alignItems: 'center',
    marginBottom: verticalScale(-20),
    height: verticalScale(30),
  },
  celebrationStarLeft: {
    position: 'absolute',
    left: scale(-40),
    top: 0,
    width: scale(32),
    height: scale(32),
    opacity: 0.6,
  },
  celebrationStarRight: {
    position: 'absolute',
    right: scale(-40),
    top: 0,
    width: scale(28),
    height: scale(28),
    opacity: 0.6,
  },
  mainContent: {
    width: '100%',
    gap: verticalScale(48),
    alignItems: 'center',
  },
  daysContainer: {
    alignItems: 'center',
    gap: verticalScale(4),
  },
  daysNumber: {
    fontSize: moderateScale(72),
    fontFamily: 'DMSans-ExtraBold',
    color: Colors.gray[80],
    lineHeight: moderateScale(80),
    letterSpacing: -1.44,
    textAlign: 'center',
  },
  daysLabel: {
    fontSize: moderateScale(20),
    fontFamily: 'DMSans-Regular',
    color: Colors.gray[40],
    lineHeight: moderateScale(28),
    letterSpacing: -0.2,
    textAlign: 'center',
  },
  encouragementText: {
    fontSize: moderateScale(24),
    fontFamily: 'DMSans-Bold',
    color: Colors.gray[80],
    lineHeight: moderateScale(32),
    letterSpacing: -0.288,
    textAlign: 'center',
  },
  weekContainer: {
    width: '100%',
    gap: verticalScale(16),
    alignItems: 'center',
  },
  weekDays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'flex-start',
  },
  dayItem: {
    flex: 1,
    alignItems: 'center',
    gap: verticalScale(12),
  },
  dayLabel: {
    fontSize: moderateScale(14),
    fontFamily: 'DMSans-Regular',
    color: Colors.gray[60],
    lineHeight: moderateScale(20),
    letterSpacing: -0.084,
    textAlign: 'center',
  },
  dayIcon: {
    width: scale(32),
    height: scale(32),
  },
  emptyCircle: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: Colors.gray[20] || '#E5E7EB',
  },
  summaryText: {
    fontSize: moderateScale(14),
    fontFamily: 'DMSans-Regular',
    color: Colors.gray[60],
    lineHeight: moderateScale(20),
    letterSpacing: -0.084,
    textAlign: 'center',
    paddingHorizontal: scale(20),
  },
  buttonContainer: {
    width: '100%',
    marginTop: verticalScale(4),
  },
});

